# How to import dataset in using python library
Written by: Aziz Baloch\
Date: 09/06/2026\
Email: itxaziz25@gmail.com

In [3]:
import pandas as pd

In [4]:

df = pd.read_excel("pandas_01_day6.xlsx")
df

    height   weight favourite_dish
0       5.8     101  Chicken Pulao
1       6.2      92        Biryani
2       5.9      62  Karahi Ghosht
3       5.9      95  Chicken Pulao
4       5.9      55  Chicken Pulao
..      ...     ...            ...
82      5.4      55          Pasta
83      5.9      75  Karahi Ghosht
84      5.4      61        Biryani
85      6.2      68  Chicken Pulao
86      5.1      96        Biryani

[87 rows x 3 columns]

In [5]:
# Column names ko clean kar lein (taaki koi accidental space na ho)
df.columns = df.columns.str.strip()

# 2. Type Casting with debugging
# Height ko float mein convert karna
df['height'] = pd.to_numeric(df['height'], errors='coerce')

# Weight ko integer mein convert karna
df['weight'] = pd.to_numeric(df['weight'], errors='coerce').astype('Int64') 

# Favorite dish ko category mein
df['favourite_dish'] = df['favourite_dish'].astype('string').str.strip().astype('category')

# 3. Agar koi value convert hone mein error de (NaN ban jaye), toh uska pata lagana
if df.isnull().values.any():
    print("Warning: Kuch values mein problem thi aur wo NaN ban gayi hain:") 
    print(df[df.isnull().any(axis=1)])

print("\n--- Data Types Successfully Changed ---")
print(df.dtypes)

#except Exception as e:
  #  print(f"Error aaya: {e}")

--- Data Types Successfully Changed ---
height             float64
weight               Int64
favourite_dish    category
dtype: object

## View dataframes in python using pandas.

In [6]:
df.head()  #its shows starting 5 rows of data.

   height  weight favourite_dish
0     5.8     101  Chicken Pulao
1     6.2      92        Biryani
2     5.9      62  Karahi Ghosht
3     5.9      95  Chicken Pulao
4     5.9      55  Chicken Pulao

In [6]:
df.tail()  #its shows last 5 rows of data.

   height (feet and inches)   weight (Kg) favourite_dish
82                       5.4           55          Pasta
83                       5.9           75  Karahi Ghosht
84                       5.4           61        Biryani
85                       6.2           68  Chicken Pulao
86                       5.1           96        Biryani

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   height          87 non-null     float64
 1   weight          87 non-null     Int64
 2   favourite_dish  87 non-null     category
dtypes: Int64(1), category(1), float64(1)
memory usage: 1.7 KB

In [8]:
df.index

RangeIndex(start=0, stop=87, step=1)

In [9]:
df.describe()

          height     weight
count  87.000000       87.0
mean    5.551264  70.517241
std     0.328916  16.771281
min     5.000000       25.0
25%     5.300000       60.0
50%     5.600000       70.0
75%     5.800000       80.0
max     6.200000      125.0

In [10]:
df.T #transpose. rows to columns

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
height,5.8,6.2,5.9,5.9,5.9,5.3,5.6,5.9,5.1,5.4,...,5.5,5.11,5.3,5.4,5.5,5.4,5.9,5.4,6.2,5.1
weight,101,92,62,95,55,59,50,76,78,68,...,85,72,62,55,52,55,75,61,68,96
favourite_dish,Chicken Pulao,Biryani,Karahi Ghosht,Chicken Pulao,Chicken Pulao,Biryani,Pasta,Biryani,Biryani,Biryani,...,Biryani,Karahi Ghosht,Biryani,Pasta,Karahi Ghosht,Pasta,Karahi Ghosht,Biryani,Chicken Pulao,Biryani

In [11]:
df.sort_index()

    height  weight favourite_dish
0      5.8     101  Chicken Pulao
1      6.2      92        Biryani
2      5.9      62  Karahi Ghosht
3      5.9      95  Chicken Pulao
4      5.9      55  Chicken Pulao
..     ...     ...            ...
82     5.4      55          Pasta
83     5.9      75  Karahi Ghosht
84     5.4      61        Biryani
85     6.2      68  Chicken Pulao
86     5.1      96        Biryani

[87 rows x 3 columns]

In [12]:
df.sort_index(ascending=False)

    height  weight favourite_dish
86     5.1      96        Biryani
85     6.2      68  Chicken Pulao
84     5.4      61        Biryani
83     5.9      75  Karahi Ghosht
82     5.4      55          Pasta
..     ...     ...            ...
4      5.9      55  Chicken Pulao
3      5.9      95  Chicken Pulao
2      5.9      62  Karahi Ghosht
1      6.2      92        Biryani
0      5.8     101  Chicken Pulao

[87 rows x 3 columns]

# Summary: 
### sort_values() sirf ek tarteeb dene ka tool hai. Agar aapko specific data nikalna hai (jaise sirf 100kg wale), toh aap Filtering (pichla wala tareeka) use karenge. Agar aapko rank ya order dekhna hai, toh Sorting use karenge.

In [13]:
df.sort_values(by="weight")  #sabse halka banda pehle

    height  weight favourite_dish
26     5.0      25        Biryani
35     5.0      31        Biryani
44     5.2      48        Biryani
42     5.6      49  Chicken Pulao
40     5.0      50  Chicken Pulao
..     ...     ...            ...
86     5.1      96        Biryani
0      5.8     101  Chicken Pulao
33     5.1     103    Chapel Kaba
34     6.0     110    Chapel Kaba
75     6.0     125    Chapel Kaba

[87 rows x 3 columns]

In [14]:
df.sort_values(by="weight", ascending=False) # Sabse wazni banda pehle

    height  weight favourite_dish
75     6.0     125    Chapel Kaba
34     6.0     110    Chapel Kaba
33     5.1     103    Chapel Kaba
0      5.8     101  Chicken Pulao
86     5.1      96        Biryani
..     ...     ...            ...
25     6.0      50        Biryani
42     5.6      49  Chicken Pulao
44     5.2      48        Biryani
35     5.0      31        Biryani
26     5.0      25        Biryani

[87 rows x 3 columns]

In [2]:
df.sort_values(by=["height", "weight"])

NameError: name 'df' is not defined

In [16]:
# Sabse wazni 5 log dekhne ke liye
df.sort_values(by="weight", ascending=False).head(5)

    height  weight favourite_dish
75     6.0     125    Chapel Kaba
34     6.0     110    Chapel Kaba
33     5.1     103    Chapel Kaba
0      5.8     101  Chicken Pulao
86     5.1      96        Biryani

# Assignment:
reason of these two things df.index (without bracket),\ Second one is df.info() with bracket.

Yeh bahut achha aur logical sawal hai. Programming mein iska seedha sa jawab hai: **"Action"** vs **"Property"**.

Python (aur Pandas) mein iska farq samajhne ke liye in dono ko aise dekho:

### 1. `df.info()` — Yeh ek "Action" (Method/Function) hai

Jab aap kisi cheez ke saath `()` lagate hain, toh aap Python se keh rahe hote hain: **"Bhai, ye kaam kar ke dikhao"** (Execute this action).

* **`df.info()`** ek function/method hai. Jab aap ise call karte hain, toh Python peeche background mein ek lambi calculation karta hai:
* Woh poori memory check karta hai.
* Column ke types dekhta hai.
* Phir ek report generate karke screen par print karta hai.


* **Reason:** Kyunki isko bahut saara kaam (computation) karna padta hai, isliye `()` ka matlab hai "Abhi process start karo".

### 2. `df.index` — Yeh ek "Property" (Attribute) hai

Jab aap bina `()` ke likhte hain, toh aap Python se keh rahe hote hain: **"Bhai, mujhe is cheez ki details la kar do"** (Give me this information).

* **`df.index`** ek property ya attribute hai. Yeh koi nayi calculation nahi kar raha, balki yeh DataFrame ke andar pehle se store ki hui ek value/list hai.
* **Reason:** Yeh ek "Static" cheez hai. DataFrame ko pata hai ki uski index kya hai, bas aapne uska data mang liya. Isliye `()` ki zaroorat nahi hoti, kyunki aap koi action nahi karwa rahe, sirf "info" check kar rahe hain.

---

### Ek Simple Example se samjho:

Socho tumhare paas ek **"Mobile Phone"** hai:

1. **`phone.call()`** (Action): Iske saath `()` lagna zaroori hai. Kyunki ye ek process hai—network dhoondhna, call milana, baat karwana.
2. **`phone.battery`** (Property): Iske saath `()` ki zaroorat nahi hai. Kyunki phone mein battery ka level pehle se "record" hai. Aap bas uska current status dekh rahe hain.

---

### Yaad rakhne ka asaan tarika:

* **`()` (Method/Function):** Jab aapko koi **kaam** karwana ho, koi analysis run karni ho, ya data change karna ho. (Example: `df.describe()`, `df.head()`, `df.dropna()`)
* **No `()` (Attribute/Property):** Jab aapko sirf **data ki value** ya koi **feature** check karna ho jo pehle se wahan mojood hai. (Example: `df.shape`, `df.columns`, `df.dtypes`)

**Ek chhoti si warning:** Agar aap `df.info` (bina brackets ke) likhoge, toh Python error nahi dega, lekin woh aapko result nahi dikhayega. Woh sirf ye batayega ki: *"Yeh ek function object hai jo yahan stored hai"*. Kyunki aapne use "kaam karne ka order" (`()`) nahi diya.