In [2]:
import numpy as np

import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=6)

dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-03  1.811245 -1.764546  0.448927 -1.395834
2013-01-04  0.450626 -0.824448 -0.624153 -0.947225
2013-01-05  0.698824  1.130257  1.090754 -0.384426
2013-01-06 -0.159491  0.020443 -0.628816 -0.204320

# Dictionary

In [6]:
# aziz is key value, 5.4 is key ki real value.

dict = {'Aziz':5.4, 'Nandlal':5.3}

dict

{'Aziz': 5.4, 'Nandlal': 5.3}

In [7]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [8]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [9]:
df2.info()

<class 'pandas.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      datetime64[us]
 2   C       4 non-null      float32
 3   D       4 non-null      int32
 4   E       4 non-null      category
 5   F       4 non-null      str
dtypes: category(1), datetime64[us](1), float32(1), float64(1), int32(1), str(1)
memory usage: 180.0 bytes

In [10]:
df2.head()

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [11]:
df2.tail()

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [14]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [15]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [16]:
df.to_numpy()

array([[ 0.74042208,  0.61976838, -0.52195909,  1.00701022],
       [-0.25549599, -1.34761524,  0.66667883,  0.20867614],
       [ 1.81124511, -1.76454563,  0.4489269 , -1.39583351],
       [ 0.45062639, -0.82444753, -0.62415321, -0.9472253 ],
       [ 0.69882407,  1.13025672,  1.0907538 , -0.3844256 ],
       [-0.15949114,  0.02044269, -0.62881608, -0.20432035]])

In [17]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.547688 -0.361023  0.071905 -0.286020
std    0.749826  1.139244  0.756589  0.848751
min   -0.255496 -1.764546 -0.628816 -1.395834
25%   -0.006962 -1.216823 -0.598605 -0.806525
50%    0.574725 -0.402002 -0.036516 -0.294373
75%    0.730023  0.469937  0.612241  0.105427
max    1.811245  1.130257  1.090754  1.007010

In [18]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.740422   -0.255496    1.811245    0.450626    0.698824   -0.159491
B    0.619768   -1.347615   -1.764546   -0.824448    1.130257    0.020443
C   -0.521959    0.666679    0.448927   -0.624153    1.090754   -0.628816
D    1.007010    0.208676   -1.395834   -0.947225   -0.384426   -0.204320

In [19]:
df

                   A         B         C         D
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-03  1.811245 -1.764546  0.448927 -1.395834
2013-01-04  0.450626 -0.824448 -0.624153 -0.947225
2013-01-05  0.698824  1.130257  1.090754 -0.384426
2013-01-06 -0.159491  0.020443 -0.628816 -0.204320

In [22]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  1.007010 -0.521959  0.619768  0.740422
2013-01-02  0.208676  0.666679 -1.347615 -0.255496
2013-01-03 -1.395834  0.448927 -1.764546  1.811245
2013-01-04 -0.947225 -0.624153 -0.824448  0.450626
2013-01-05 -0.384426  1.090754  1.130257  0.698824
2013-01-06 -0.204320 -0.628816  0.020443 -0.159491

## Assignment:

# axis = 1 means ke hum column ko access kr rhy hai ya change kr rhy hai through the sort_index() function.
# axis = 0 means ke hum rows ko access kr rhy hai ya change kr rhy hai through the sort_index() function.

In [24]:
df.sort_values(by='A')

                   A         B         C         D
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-06 -0.159491  0.020443 -0.628816 -0.204320
2013-01-04  0.450626 -0.824448 -0.624153 -0.947225
2013-01-05  0.698824  1.130257  1.090754 -0.384426
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-03  1.811245 -1.764546  0.448927 -1.395834

In [25]:
df

                   A         B         C         D
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-03  1.811245 -1.764546  0.448927 -1.395834
2013-01-04  0.450626 -0.824448 -0.624153 -0.947225
2013-01-05  0.698824  1.130257  1.090754 -0.384426
2013-01-06 -0.159491  0.020443 -0.628816 -0.204320

In [26]:
df['A']

2013-01-01    0.740422
2013-01-02   -0.255496
2013-01-03    1.811245
2013-01-04    0.450626
2013-01-05    0.698824
2013-01-06   -0.159491
Freq: D, Name: A, dtype: float64

In [27]:
df[['A','B']]

                   A         B
2013-01-01  0.740422  0.619768
2013-01-02 -0.255496 -1.347615
2013-01-03  1.811245 -1.764546
2013-01-04  0.450626 -0.824448
2013-01-05  0.698824  1.130257
2013-01-06 -0.159491  0.020443

In [28]:
df[0:3]

                   A         B         C         D
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-03  1.811245 -1.764546  0.448927 -1.395834

In [29]:
df.shape

(6, 4)

In [34]:
df

                   A         B         C         D
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-03  1.811245 -1.764546  0.448927 -1.395834
2013-01-04  0.450626 -0.824448 -0.624153 -0.947225
2013-01-05  0.698824  1.130257  1.090754 -0.384426
2013-01-06 -0.159491  0.020443 -0.628816 -0.204320

In [33]:
#indexing range in columns
df.iloc[:,0:2]

                   A         B
2013-01-01  0.740422  0.619768
2013-01-02 -0.255496 -1.347615
2013-01-03  1.811245 -1.764546
2013-01-04  0.450626 -0.824448
2013-01-05  0.698824  1.130257
2013-01-06 -0.159491  0.020443

In [ ]:
#indexing range in rows
df.iloc[0:4, :] # iloc use hota hai index ko lock krne ke liye.

                   A         B         C         D
2013-01-01  0.740422  0.619768 -0.521959  1.007010
2013-01-02 -0.255496 -1.347615  0.666679  0.208676
2013-01-03  1.811245 -1.764546  0.448927 -1.395834
2013-01-04  0.450626 -0.824448 -0.624153 -0.947225

In [ ]:
# loc indexing column wise hoti hai but Srings ke sath like name column ka name de kr.
# loc function simple loc ke liye use hoti hai kisi bhi column ya row ko but as a string call krke bula skty hai. 
df.loc[:,'A':'B']

                   A         B
2013-01-01  0.740422  0.619768
2013-01-02 -0.255496 -1.347615
2013-01-03  1.811245 -1.764546
2013-01-04  0.450626 -0.824448
2013-01-05  0.698824  1.130257
2013-01-06 -0.159491  0.020443

In [44]:
df.iloc[3].T

A    0.450626
B   -0.824448
C   -0.624153
D   -0.947225
Name: 2013-01-04 00:00:00, dtype: float64

In [45]:
import seaborn as sns

In [48]:
kashti = sns.load_dataset('titanic')
kashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [49]:
kashti.sample(100)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
574,0,3,male,16.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
589,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
618,1,2,female,4.0,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
541,0,3,female,9.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
171,0,3,male,4.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
296,0,3,male,23.5,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
749,0,3,male,31.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
642,0,3,female,2.0,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False

In [52]:
kashti[kashti['age'] < 5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
63,0,3,male,4.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
171,0,3,male,4.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
374,0,3,female,3.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
386,0,3,male,1.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
407,1,2,male,3.00,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
530,1,2,female,2.00,1,1,26.0000,S,Second,child,False,NaN,Southampton,yes,False
618,1,2,female,4.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
642,0,3,female,2.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
691,1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False
750,1,2,female,4.00,1,1,23.0000,S,Second,child,False,NaN,Southampton,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
824,0,3,male,2.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [54]:
kashti[kashti['fare'] < 5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
179,0,3,male,36.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
263,0,1,male,40.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
277,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
378,0,3,male,20.0,0,0,4.0125,C,Third,man,True,NaN,Cherbourg,no,True
413,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
466,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
822,0,1,male,38.0,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True