# How to import dataset in python using pandas library.
Written by: Aziz Rind\
Date: 09/06/2026\
Email: itxaziz25@gmail.com

In [ ]:
pip install pandas

In [3]:
# step_1 importing libraries
import pandas as pd

In [ ]:
# step_2 reading/importing dataset.
df = pd.read_excel("pandas_01_day6.xlsx")
df

   height (feet and inches)   weight (Kg) favourite_dish
0                        5.8          101  Chicken Pulao
1                        6.2           92        Biryani
2                        5.9           62  Karahi Ghosht
3                        5.9           95  Chicken Pulao
4                        5.9           55  Chicken Pulao
..                       ...          ...            ...
82                       5.4           55          Pasta
83                       5.9           75  Karahi Ghosht
84                       5.4           61        Biryani
85                       6.2           68  Chicken Pulao
86                       5.1           96        Biryani

[87 rows x 3 columns]

## View dataframes using python in pandas

In [15]:
df.head(7)

  height (feet and inches)   weight (Kg) favourite_dish
0                       5.8          101  Chicken Pulao
1                       6.2           92        Biryani
2                       5.9           62  Karahi Ghosht
3                       5.9           95  Chicken Pulao
4                       5.9           55  Chicken Pulao
5                       5.3           59        Biryani
6                       5.6           50          Pasta

In [16]:
df.tail(7)

   height (feet and inches)   weight (Kg) favourite_dish
80                       5.4           55          Pasta
81                       5.5           52  Karahi Ghosht
82                       5.4           55          Pasta
83                       5.9           75  Karahi Ghosht
84                       5.4           61        Biryani
85                       6.2           68  Chicken Pulao
86                       5.1           96        Biryani

In [14]:
df.shape

(87, 3)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   height (feet and inches)   87 non-null     str
 1   weight (Kg)                87 non-null     int64
 2   favourite_dish             87 non-null     str
dtypes: int64(1), str(2)
memory usage: 2.2 KB

In [19]:
df.index

RangeIndex(start=0, stop=87, step=1)

In [20]:
df.columns

Index(['height (feet and inches) ', 'weight (Kg)', 'favourite_dish'], dtype='str')

In [24]:
df.describe()

       weight (Kg)
count    87.000000
mean     70.459770
std      16.753899
min      25.000000
25%      60.000000
50%      70.000000
75%      80.000000
max     125.000000

In [ ]:
df.T # transpose data

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
height (feet and inches),5.8,6.2,5.9,5.9,5.9,5.3,5.6,5.9,5.1,5.4,...,5.5,5.11,5.3,5.4,5.5,5.4,5.9,5.4,6.2,5.1
weight (Kg),101,92,62,95,55,59,50,76,78,68,...,85,72,62,55,52,55,75,61,68,96
favourite_dish,Chicken Pulao,Biryani,Karahi Ghosht,Chicken Pulao,Chicken Pulao,Biryani,Pasta,Biryani,Biryani,Biryani,...,Biryani,Karahi Ghosht,Biryani,Pasta,Karahi Ghosht,Pasta,Karahi Ghosht,Biryani,Chicken Pulao,Biryani